title: My Jekyll Blog with Tailwind CSS
description: A blog powered by Jekyll and styled with Tailwind CSS.
baseurl: "/Jekyll-blog"
url: "https://ltxstudio.github.io"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - node_modules
