title: "My Enhanced Jekyll Blog"
description: "A feature-rich blog powered by Jekyll and Tailwind CSS."
url: ""
baseurl: ""
theme: minima
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives

paginate: 5
paginate_path: "/page:num/"

disqus:
  shortname: your-disqus-shortname

social_links:
  twitter: https://twitter.com/yourhandle
  linkedin: https://linkedin.com/in/yourprofile
  github: https://github.com/yourusername
